replicaCount: 1

image:
  repository: raviiprakashh/go-app
  pullPolicy: IfNotPresent
  tag: "bd22b01d9c278e10752db8fa6cdfc903c91b6f42"


ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific